### ISSUE TITLE
User Management Checklist

### ISSUE THREAD

**Issue by pilarArr** [upm-space/dO2s#24]
- [ ] Check that an admin can't delete another admin
- [ ] Do we send user a warning that the password was changed by the admin?
- [ ] Add roles support
- [ ] Decide if we allow users in the trash to log in.
